name: repo-setup

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  common:
    uses: ./.github/workflows/repo-setup-common.yml
    secrets: inherit
    with:
      actions-to-run: 'all'
      branches: 'master, develop'
      default-branch: 'develop'
      team: 'ASD'
      admins: 'malipui, sjayakandan'
      branch-age: '30'
