name: repo-setup

on:
  schedule: 
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  common:
    uses: yardcooper/workflows-common/.github/workflows/repo-setup-common.yml@main
    secrets: inherit
    with: 
      actions-to-run: "all"
      branches: "main, develop"
      default-branch: "develop"
      team: "ASD"
      admins: "malipui, sjayakandan"
      branch-age: "30"